In [1]:
import pandas as pd

In [6]:
data

,Mission_id,N_Recommandation,Recommandation,Evaluation,Recommendation_status,Action_id,Action,Échéance,Action_status
0,M0001,R0001,Mettre en place une politique de gestion des a...,Critique,accepté,A0001,Élaborer et diffuser la politique d'accès,2025-06-30,En cours
1,M0001,R0001,Mettre en place une politique de gestion des a...,Critique,accepté,A0002,Former les équipes IT sur la nouvelle politique,2025-07-15,Non échues
2,M0001,R0002,Renforcer les contrôles sur les journaux d'audit,Modéré,rejeté,NaN,NaN,NaN,NaN
3,M0001,R0003,Séparer les environnements de production et de...,Critique,accepté,A0003,Déployer un environnement de staging dédié,2025-08-01,En cours
4,M0001,R0004,Chiffrer les données sensibles en transit,Critique,accepté,A0004,Implémenter TLS 1.3 sur tous les services exposés,2025-09-01,Non échues
5,M0002,R0005,Sécuriser les échanges inter-services,Modéré,accepté,A0004,Implémenter TLS 1.3 sur tous les services exposés,2025-09-01,Non échues
6,M0002,R0006,Mettre en œuvre une procédure de sauvegarde fo...,Critique,accepté,A0005,Rédiger et valider la procédure de backup,2025-05-31,Clôturées
7,M0002,R0006,Mettre en œuvre une procédure de sauvegarde fo...,Critique,accepté,A0006,Tester les restaurations mensuellement,En continue,En continue
8,M0002,R0007,Documenter les procédures de reprise d'activité,Modéré,accepté,A0007,Rédiger le PRA et le faire valider par la DSI,2025-07-01,En retard
9,M0002,R0008,Réviser la politique de rétention des logs,Mineur,en etude,NaN,NaN,NaN,NaN
10,M0003,R0009,Mettre en place un processus de gestion des vu...,Critique,accepté,A0008,Déployer un outil de scan de vulnérabilités,2025-06-15,En cours
11,M0003,R0009,Mettre en place un processus de gestion des vu...,Critique,accepté,A0009,Définir un processus de patch management,2025-07-30,Non échues
12,M0003,R0010,Encadrer l'utilisation des comptes à privilèges,Critique,accepté,A0010,Déployer une solution PAM,2025-10-01,Non échues
13,M0003,R0011,Sensibiliser les collaborateurs aux risques de...,Modéré,accepté,A0011,Organiser des campagnes de sensibilisation tri...,En continue,En continue
14,M0003,R0012,Formaliser la gestion des incidents de sécurité,Modéré,rejeté,NaN,NaN,NaN,NaN
15,M0003,R0013,Mettre en place un SIEM pour la détection des ...,Critique,accepté,A0012,Déployer et configurer un SIEM,2025-12-01,Non échues
16,M0004,R0014,Centraliser la supervision des événements de s...,Critique,accepté,A0012,Déployer et configurer un SIEM,2025-12-01,Non échues
17,M0004,R0015,Mettre à jour le registre des traitements RGPD,Modéré,accepté,A0013,Inventorier et documenter tous les traitements...,2025-06-01,Clôturées
18,M0004,R0016,Nommer un DPO et définir ses responsabilités,Critique,accepté,A0014,Publier la fiche de poste et recruter le DPO,2025-07-01,En retard
19,M0004,R0017,Encadrer les transferts de données hors UE,Modéré,en etude,NaN,NaN,NaN,NaN
20,M0004,R0018,Mettre en place des clauses contractuelles RGP...,Mineur,accepté,A0015,Rédiger et signer les avenants contractuels,2025-08-15,Non échues
21,M0005,R0019,Revoir la procédure de contrôle interne des pa...,Critique,accepté,A0016,Cartographier le processus de paiement existant,2025-05-20,Clôturées
22,M0005,R0019,Revoir la procédure de contrôle interne des pa...,Critique,accepté,A0017,Implémenter un double contrôle sur les virements,2025-06-30,En cours
23,M0005,R0020,Automatiser les rapprochements bancaires,Modéré,accepté,A0018,Intégrer un module de rapprochement dans l'ERP,2025-09-01,Non échues
24,M0005,R0021,Documenter les délégations de signature,Modéré,rejeté,NaN,NaN,NaN,NaN
25,M0005,R0022,Mettre en place un suivi des immobilisations,Mineur,accepté,A0019,Réaliser un inventaire physique des actifs,2025-07-31,En retard
26,M0005,R0023,Former les équipes finance aux nouvelles norme...,Modéré,accepté,A0020,Organiser un cycle de formation IFRS,2025-10-01,Rééchelonnées
27,M0005,R0024,Mettre à jour les procédures comptables selon ...,Modéré,accepté,A0020,Organiser un cycle de formation IFRS,2025-10-01,Rééchelonnées
28,M0005,R0025,Renforcer le contrôle des notes de frais,Mineur,en etude,NaN,NaN,NaN,NaN
29,M0005,R0026,Réviser la politique de provisionnement des cr...,Critique,accepté,A0021,Mettre à jour les règles de provisionnement da...,2025-11-01,Non échues

In [15]:
import numpy as np
from datetime import  date 
print(date.today())
data['Échéance'] = data['Échéance'].replace("En continue",np.nan)

2026-05-17

In [31]:
data

,Mission_id,N_Recommandation,Recommandation,Evaluation,Recommendation_status,Action_id,Action,Échéance,Action_status
0,M0001,R0001,Mettre en place une politique de gestion des a...,Critique,accepté,A0001,Élaborer et diffuser la politique d'accès,2025-06-30,En cours
1,M0001,R0001,Mettre en place une politique de gestion des a...,Critique,accepté,A0002,Former les équipes IT sur la nouvelle politique,2025-07-15,Non échues
2,M0001,R0002,Renforcer les contrôles sur les journaux d'audit,Modéré,rejeté,NaN,NaN,NaT,NaN
3,M0001,R0003,Séparer les environnements de production et de...,Critique,accepté,A0003,Déployer un environnement de staging dédié,2025-08-01,En cours
4,M0001,R0004,Chiffrer les données sensibles en transit,Critique,accepté,A0004,Implémenter TLS 1.3 sur tous les services exposés,2025-09-01,Non échues
5,M0002,R0005,Sécuriser les échanges inter-services,Modéré,accepté,A0004,Implémenter TLS 1.3 sur tous les services exposés,2025-09-01,Non échues
6,M0002,R0006,Mettre en œuvre une procédure de sauvegarde fo...,Critique,accepté,A0005,Rédiger et valider la procédure de backup,2025-05-31,Clôturées
7,M0002,R0006,Mettre en œuvre une procédure de sauvegarde fo...,Critique,accepté,A0006,Tester les restaurations mensuellement,NaT,En continue
8,M0002,R0007,Documenter les procédures de reprise d'activité,Modéré,accepté,A0007,Rédiger le PRA et le faire valider par la DSI,2025-07-01,En retard
9,M0002,R0008,Réviser la politique de rétention des logs,Mineur,en etude,NaN,NaN,NaT,NaN
10,M0003,R0009,Mettre en place un processus de gestion des vu...,Critique,accepté,A0008,Déployer un outil de scan de vulnérabilités,2025-06-15,En cours
11,M0003,R0009,Mettre en place un processus de gestion des vu...,Critique,accepté,A0009,Définir un processus de patch management,2025-07-30,Non échues
12,M0003,R0010,Encadrer l'utilisation des comptes à privilèges,Critique,accepté,A0010,Déployer une solution PAM,2025-10-01,Non échues
13,M0003,R0011,Sensibiliser les collaborateurs aux risques de...,Modéré,accepté,A0011,Organiser des campagnes de sensibilisation tri...,NaT,En continue
14,M0003,R0012,Formaliser la gestion des incidents de sécurité,Modéré,rejeté,NaN,NaN,NaT,NaN
15,M0003,R0013,Mettre en place un SIEM pour la détection des ...,Critique,accepté,A0012,Déployer et configurer un SIEM,2025-12-01,Non échues
16,M0004,R0014,Centraliser la supervision des événements de s...,Critique,accepté,A0012,Déployer et configurer un SIEM,2025-12-01,Non échues
17,M0004,R0015,Mettre à jour le registre des traitements RGPD,Modéré,accepté,A0013,Inventorier et documenter tous les traitements...,2025-06-01,Clôturées
18,M0004,R0016,Nommer un DPO et définir ses responsabilités,Critique,accepté,A0014,Publier la fiche de poste et recruter le DPO,2025-07-01,En retard
19,M0004,R0017,Encadrer les transferts de données hors UE,Modéré,en etude,NaN,NaN,NaT,NaN
20,M0004,R0018,Mettre en place des clauses contractuelles RGP...,Mineur,accepté,A0015,Rédiger et signer les avenants contractuels,2025-08-15,Non échues
21,M0005,R0019,Revoir la procédure de contrôle interne des pa...,Critique,accepté,A0016,Cartographier le processus de paiement existant,2025-05-20,Clôturées
22,M0005,R0019,Revoir la procédure de contrôle interne des pa...,Critique,accepté,A0017,Implémenter un double contrôle sur les virements,2025-06-30,En cours
23,M0005,R0020,Automatiser les rapprochements bancaires,Modéré,accepté,A0018,Intégrer un module de rapprochement dans l'ERP,2025-09-01,Non échues
24,M0005,R0021,Documenter les délégations de signature,Modéré,rejeté,NaN,NaN,NaT,NaN
25,M0005,R0022,Mettre en place un suivi des immobilisations,Mineur,accepté,A0019,Réaliser un inventaire physique des actifs,2025-07-31,En retard
26,M0005,R0023,Former les équipes finance aux nouvelles norme...,Modéré,accepté,A0020,Organiser un cycle de formation IFRS,2025-10-01,Rééchelonnées
27,M0005,R0024,Mettre à jour les procédures comptables selon ...,Modéré,accepté,A0020,Organiser un cycle de formation IFRS,2025-10-01,Rééchelonnées
28,M0005,R0025,Renforcer le contrôle des notes de frais,Mineur,en etude,NaN,NaN,NaT,NaN
29,M0005,R0026,Réviser la politique de provisionnement des cr...,Critique,accepté,A0021,Mettre à jour les règles de provisionnement da...,2025-11-01,Non échues

In [35]:
data.to_csv("mockup_data_V1.csv")

In [33]:
data['Action_status'].unique()

array(['En cours', 'Non échues', nan, 'Clôturées', 'En continue',
       'En retard', 'Rééchelonnées'], dtype=object)

In [42]:
if data["Échéance"].dtype == "object":
    print("the datetime is obejct")

fuck

In [11]:
data['Échéance'] = pd.to_datetime(data['Échéance'],format="%Y-%m-%d")

In [20]:
data['Échéance'].value_counts()

Échéance
2025-09-01    3
2025-10-01    3
2025-07-01    2
2025-12-01    2
2025-06-30    2
2025-08-01    1
2025-07-15    1
2025-06-15    1
2025-05-31    1
2025-07-30    1
2025-06-01    1
2025-08-15    1
2025-05-20    1
2025-07-31    1
2025-11-01    1
Name: count, dtype: int64

In [30]:
action_echue = (
    data.loc[data["Échéance"] <= "2025-06-01"]['Action_id']
    .nunique()
)

action_continue = (
    data.loc[data["Action_status"] <= "En continue"]['Action_id']
    .nunique()
)
print('action en continue :',action_continue)
print('action echue :',action_echue)

action en continue : 5
action echue : 3

In [ ]:
# global KPis 
(data[["Recommendation_status","Recommandation"]]
    .groupby(["Recommendation_status"])
    .nunique().reset_index()
    ).set_index("Recommendation_status")["Recommandation"].to_dict()

{'accepté': 20, 'en etude': 3, 'rejeté': 3}

##### **Recommandations**
- Nombre de recommandations non acceptées
- Nombre de recommandation à l’étude
- Répartition du nombre de recommandations acceptées  par criticité  (critique, modéré, mineur)
##### **Actions**
---
- Nombre total d’actions
- Répartition du nombre d’actions par criticité  (critique, modéré, mineur)
- Répartition par statut (non échues, en cours, clôturées, en continue, en retard, rééchelonné)

- Taux d’acceptation de recommandation = Nombre de recommandations acceptées / Nombre total de recommandations

- Taux de mise en œuvre des actions = Nombre d’actions réalisées / Nombre total d’actions

- Taux de mise en œuvre des actions critiques = Nombre d’actions critiques réalisées / Nombre total d’actions critiques

In [4]:
data.columns

Index(['Mission_id', 'N_Recommandation', 'Recommandation', 'Evaluation',
       'Recommendation_status', 'Action_id', 'Action', 'Échéance',
       'Action_status'],
      dtype='object')

In [5]:
data = pd.read_csv('mock_data.csv')

In [6]:
# Mission 
agg_dict = {
    f"Nb_{status}": (
        "N_Recommandation",
        lambda x, status=status: x[data.loc[x.index, "Recommendation_status"] == status ].nunique()
    )
    for status in data["Recommendation_status"].unique()
}

agg_dict["total_recommendation"] = (
    "N_Recommandation",
    "nunique"
)

tableau_1 = (
    data.groupby("Mission_id")
    .agg(**agg_dict)
    .reset_index()
)

tableau_1

  Mission_id  Nb_accepté  Nb_rejeté  Nb_en etude  total_recommendation
0      M0001           3          1            0                     4
1      M0002           3          0            1                     4
2      M0003           4          1            0                     5
3      M0004           4          0            1                     5
4      M0005           6          1            1                     8

In [7]:
recommed_KPis = {}
recommed_KPis["Total_recom"] = tableau_1["total_recommendation"].sum().item()
recommed_KPis["Total_recom_ACC"] = tableau_1["Nb_accepté"].sum().item()
recommed_KPis["Total_recom_Rej"] = tableau_1["Nb_rejeté"].sum().item()
recommed_KPis["Total_recom_etu"] = tableau_1["Nb_en etude"].sum().item()
recommed_KPis["acceptation_rate"] = (round(recommed_KPis["Total_recom_ACC"]/recommed_KPis["Total_recom"],2)*100)
print(recommed_KPis["acceptation_rate"])

77.0

In [8]:
# recommendation accepte part evaluation
tableau_2 = (
    data.loc[data['Recommendation_status'] == "accepté",["N_Recommandation","Evaluation"]]
    .groupby("Evaluation")
    .agg(nb_recomendation=("N_Recommandation","nunique"))
    .reset_index()
)
tableau_2.set_index("Evaluation")["nb_recomendation"].to_dict()

{'Critique': 11, 'Mineur': 2, 'Modéré': 7}

In [9]:
# Repartution action part criticité 
tableau_2 = (
    data[["Action_id","Evaluation"]]
    .groupby("Evaluation")
    .agg(nb_action=("Action_id","nunique"))
    .reset_index()
)
tableau_2

  Evaluation  nb_action
0   Critique         14
1     Mineur          2
2     Modéré          6

In [10]:
# Repartition action part Mission 
tableau_3 = (
    data[["Action_id","Mission_id"]]
    .groupby("Mission_id")
    .agg(nb_action=("Action_id","nunique"))
    .reset_index()
)
tableau_3

  Mission_id  nb_action
0      M0001          4
1      M0002          4
2      M0003          5
3      M0004          4
4      M0005          6

In [13]:
# Repartition  action part status 
tableau_4 = (
    data[['Action_id',"Action_status"]].dropna()
    .groupby("Action_status")
    .agg(nb_action=("Action_id","nunique"))
    .reset_index()
)
tableau_4

   Action_status  nb_action
0      Clôturées          3
1    En continue          2
2       En cours          4
3      En retard          3
4     Non échues          8
5  Rééchelonnées          1

In [ ]:
# Taux d’acceptation de recommandation :T1
T1 = round(results['Nb_accepté'].sum() / results['total_recommendation'].sum(),2) * 100
T1.item()

# Taux de mise en œuvre des actions : T2
d = tableau_4.set_index("Action_status")["nb_action"].to_dict()
T2 = round((d["En continue"] + d["Clôturées"]) / tableau_4.iloc[:,1].sum(), 2) * 100
T2.item()

# Taux de mise en œuvre des actions critiques : T3
# ACR : Action Crtitique Realisé
ACR = data[
    (data["Evaluation"] == "Critique") & 
    (
        (data["Action_status"] == "Clôturées") |
        (data["Action_status"] == "En cours")
    )
    ]['Action_id'].nunique()

T3 = round(ACR / tableau_4.iloc[:,1].sum(),3) * 100
T3.item()

28.599999999999998